name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Create public directory
      run: mkdir -p public

    - name: Copy files to public directory
      run: |
        find . -maxdepth 1 ! -name public ! -name . -exec cp -r {} public/ \;

    - name: Replace API key and Map ID in map.js
      run: |
        sed -i "s/YOUR_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" public/map.js
        sed -i "s/YOUR_MAP_ID/${{ secrets.GOOGLE_MAPS_MAP_ID }}/g" public/map.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
